pipeline {
environment {
registry = "arvindkumar300430/dockerpipeline"
registryCredential = 'dockerhub_id'
dockerImage = ''
}
agent any  
stages {
        
    stage('Git') {
      steps { 
      git branch: 'dockerpipe', credentialsId: 'dockerhub_id', url: 'https://github.com/arundaemon/testdaemon.git'    
      }
    }
    stage('Build Docker image'){
          steps{
	         dockerImage = sh "cd frontend && docker.build registry + ":$BUILD_NUMBER"
          }
      }
    stage('Deploy our image') {
     steps{
       script {
	docker.withRegistry( '', registryCredential ) {
	dockerImage.push()
	}
	}
	}
} 
