---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "em-crm-msa-prod-frontend"
  namespace: "prod"
  labels:
    app: "em-crm-msa-prod-frontend"
spec:
  selector:
    matchLabels:
      app: "em-crm-msa-prod-frontend"
  template:
    metadata:
      labels:
        app: "em-crm-msa-prod-frontend"
    spec:
      containers:
      - name: "em-crm-msa-prod-frontend"
        image: "arvindkumar300430/dockerpipeline:5"
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 400Mi
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "em-crm-msa-prod-frontend"
  namespace: "prod"
  labels:
    app: "em-crm-msa-prod-frontend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "em-crm-msa-prod-frontend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: Utilization
        averageUtilization: 60
  - type: "Resource"
    resource:
      name: "memory"
      target:
        type: Utilization
        averageUtilization: 60
---        
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: em-crm-msa-prod-frontend
  name: em-crm-msa-prod-frontend
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    networking.gke.io/v1beta1.FrontendConfig: my-frontend-config
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,token,xsrf-token,Client,Client-Id,accessToken    
    nginx.ingress.kubernetes.io/cors-allow-method: PUT, GET, POST, OPTIONS, DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://prodgcp.extramarks.com, https://prodgcp-teach.extramarks.com, https://www.extramarks.com, https://teach.extramarks.com, https://preprod-teach.extramarks.com, https://preprod.extramarks.com, https://gotoschool.extramarks.com, https://elevate.extramarks.com/, https://exmprenewnemr.extramarks.com, https://exmprenewnemrteacher.extramarks.com, https://app.extramarks.com, https://crm.extramarks.com, https://api-crm.extramarks.com"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"     
spec:
  defaultBackend:       
    service:
      name: em-crm-msa-prod-frontend-service
      port:
        number: 3000  
  
 # ingressClassName: public
  rules:
  - host: em-crm.extramarks.com
  - http:
      paths:
      - backend:
          service:
            name: em-crm-msa-prod-frontend-service
            port:
              number: 3000
        path: /
        pathType: Prefix
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: my-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "em-crm-msa-prod-frontend-service"
  namespace: "prod"
  labels:
    app: "em-crm-msa-prod-frontend"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: "em-crm-msa-prod-frontend"
  type: "LoadBalancer"
  loadBalancerIP: ""
