import Env_Config from "./settings";
export const url = {
  backendHost: Env_Config.api.url,
  socketUrl: Env_Config.api.socketUrl,
  logbookApi: Env_Config.api.logbookApi,
  cubeApiUrl: Env_Config.CUBE_API_URL,
  reportEngineApiUrl: Env_Config.REPORT_ENGINE_API_ENDPOINT,
  hrmApiUrl: Env_Config.HRM_API_ENDPOINT,
  OmsApiUrl: Env_Config.OMS_API_URL,
  knowlarityUrl: Env_Config.KNOWLARITY_STREAM_URL,
  apiGateway: Env_Config.WEBSITE_URL,
};

export const ENV = {
  env: Env_Config.env,
  version: Env_Config.version,
  logbookLogin: Env_Config.api.logBookLogin,
  logbookPass: Env_Config.api.logBookPass,
};

export const endPoint = {
  call: {
    startCall: "/startcall",
  },
  users: {
    markDashboardFavourite: "/user/markDashboardFavourite",
    markReportFavourite: "/user/markReportFavourite",
    adminLogin: "/user/userLogin",
    getUsersList: "/user/getUsersList",
    createUser: "/user/createUser",
    updateUser: "/user/updateUser",
    deleteUser: "/user/deleteUser",
    generateUserToken: "/user/generateUserToken",
  },
  menus: {
    getMenusList: "/menu/getMenusList",
    deleteMenu: "/menu/deleteMenu",
    createMenu: "/menu/createMenu",
    updateMenu: "/menu/updateMenu",
    getAllMenus: "/menu/getAllMenus",
    saveRoleMenuMapping: "/menu/saveRoleMenuMapping",
    getAllSideBarMenus: "/menu/getAllSideBarMenus",
    getAllGroupedMenu: "/menu/getAllGroupedMenu",
  },
  project: {
    getProjectList: "/project/getProjectList",
    deleteProject: "/project/deleteProject",
    createProject: "/project/createProject",
    updateProject: "/project/updateProject",
    getAllProjects: "/project/getAllProjects",
  },
  cycles: {
    createCycle: "/cycle/createCycle",
    updateCycle: "/cycle/updateCycle",
    getCyclesList: "/cycle/getCyclesList",
    deleteCycle: "/cycle/deleteCycle",
    getAllCycles: "/cycle/getAllCycles",
    cycleDetails: "/cycle/cycleDetails",
    isDuplicateCycle: "/cycle/isDuplicateCycle",
    changeStatus: "/cycle/changeStatus",
    getAllCycleNames: "/cycle/getAllCycleNames",
    mapCyclesWithJourney: "/cycle/mapCyclesWithJourney",
    unMapAvailableCycle: "/cycle/unMapAvailableCycle",
  },
  journeys: {
    getJourneyList: "/journey/getJourneyList",
    createJourney: "/journey/createJourney",
    updateJourney: "/journey/updateJourney",
    deleteJourney: "/journey/deleteJourney",
    getAllJourneys: "/journey/getAllJourneys",
    getJourney: "/journey/getJourney",
    changeStatus: "/journey/changeStatus",
    getActiveJourneys: "/journey/getActiveJourneys",
    getB2BDefaultStageStatus: '/journey/getB2BDefaultStageStatus'
  },
  status: {
    createStatus: "/status/createStatus",
    updateStatus: "/status/updateStatus",
    deleteStatus: "/status/deleteStatus",
    getStatusList: "/status/getStatusList",
    changeStatus: "/status/changeStatus",
    getAllStatus: "/status/getAllStatus",
    statusDetails: "/status/statusDetails",
    isDuplicateStatus: "/status/isDuplicateStatus",
    mapStatusesWithStage: "/status/mapStatusesWithStage",
    unMapAvailableStatus: "/status/unMapAvailableStatus",
  },
  stages: {
    createStage: "/stage/createStage",
    updateStage: "/stage/updateStage",
    deleteStage: "/stage/deleteStage",
    getStageList: "/stage/getStageList",
    changeStatus: "/stage/changeStatus",
    getAllStages: "/stage/getAllStages",
    stageDetails: "/stage/stageDetails",
    isDuplicateStage: "/stage/isDuplicateStage",
    mapStagesWithCycle: "/stage/mapStagesWithCycle",
    unMapAvailableStage: "/stage/unMapAvailableStage",
    getStageByKey: "/stage/getStageByKey",
  },
  banners: {
    getBannersList: "/banner/getBannersList",
    deleteBanner: "/banner/deleteBanner",
    saveBanner: "/banner/saveBanner",
    updateBanner: "/banner/updateBanner",
    getBannerDetails: "/banner/getBannerDetails",
    updateBannerStatus: "/banner/updateBannerStatus",
    getAllActiveBanners: "/banner/getAllActiveBanners",
  },
  activities: {
    createActivity: "/activity/createActivity",
    updateActivity: "/activity/updateActivity",
    deleteActivity: "/activity/deleteActivity",
    getActivityList: "/activity/getActivityList",
    getEmployeesCount: "/activity/getEmployeeCount",
    getCustomersCount: "/activity/getCustomerCount",
    getActivity: "/activity/getActivity",
    getTrueActivity: "/activity/getTrueActivity",
    getAllActivities: "/activity/getAllActivities",
    getActivityByKey: "/activity/getActivityByKey",
    logbookActivity: "/activity/addUserActivityData",
    getActivitiesDetail: "/activity/getActivitiesDetail"
  },
  sources: {
    createSource: "/source/createSource",
    updateSource: "/source/updateSource",
    deleteSource: "/source/deleteSource",
    getSourceList: "/source/getSourceList",
    changeStatus: "/source/changeStatus",
    getAllSources: "/source/getAllSources",
    getAllSubSource: "/source/getAllSubSource",
    sourceDetails: "/source/sourceDetails",
    isDuplicateSource: "/source/isDuplicateSource",
    addSubSource: "/source/addSubSource",
    removeSubSource: "/source/removeSubSource",
    changeSubSourceStatus: "/source/changeSubSourceStatus",
    allSourcesWithLeadCount: "/source/allSourcesWithLeadCount",
  },
  rule: {
    getRuleList: "/rule/getRuleList",
    deleteRule: "/rule/deleteRule",
    createRule: "/rule/createRule",
    updateRule: "/rule/updateRule",
    getRuleDetails: "/rule/getRuleDetails",
    getRulesByRole: "/rule/getRulesByRole",
  },
  reportEngine: {
    getDataSets: "/dataset/getDataSetsList",
    getMeasuresList: "/measure/getMeasuresList",
    getReportEngineToken: "/getToken",
  },
  attendance: {
    createAttendanceMatrix: "/attendance/createAttendanceMatrix",
    getAttendanceList: "/attendance/getAttendanceList",
    updateAttendance: "/attendance/updateAttendance",
    addActivity: "/attendance/addActivity",
    updateActivity: "/attendance/updateActivity",
    attendanceDetails: "/attendance/attendanceDetails",
    changeStatus: "/attendance/changeStatus",
    getMinMaxTarget: "/attendance/getMinMaxTarget",
  },
  targetIncentiveLog: {
    getLogsList: "/targetIncentiveLog/getLogsList",
  },
  targetIncentive: {
    uploadTargetIncentive: "/targetIncentive/uploadTargetIncentive",
    downloadSample: "/targetIncentive/downloadSample",
    getTargetIncentive: "/targetIncentive/getTargetIncentive",
  },
  target: {
    downloadSampleTarget: "/target/downloadSampleTarget",
    addTarget: "/target/addTarget",
    getTargetList: "/target/getTargetList",
    getRoleNameProducts: "/target/getRoleNameProducts",
    updateTargetDetails: "/target/updateTargetDetails",
    assignTargets: "/target/assignTargets",
  },
  task: {
    createTask: "/task/createTask",
    getTaskList: "/task/getTaskList",
    deleteTask: "/task/deleteTask",
    changeStatus: "/task/changeStatus",
    updateTask: "/task/updateTask",
    getTask: "/task/getTask",
    getAllTasks: "/task/getAllTasks",
  },
  activityForm: {
    submitActivityForm: "/activityForm/createActivityForm",
  },
  taskActivityMapping: {
    getTaskActivityMappingList: "/taskActivityMapping/getTaskActivityList",
    changeStatus: "/taskActivityMapping/changeStatus",
    createTaskActivityMapping: "/taskActivityMapping/createTaskActivity",
  },
  campaign: {
    getCampaignList: "/campaign/getCampaignList",
    createCampaign: "/campaign/createCampaign",
    updateCampaign: "/campaign/updateCampaign",
    getCampaignDetails: "/campaign/campaignDetails",
  },
  territory: {
    createTerritory: "/territoryMapping/createTerritory",
    getTerritoryList: "/territoryMapping/getTerritoryList",
    getTerritoryDetails: "/territoryMapping/getTerritoryDetails",
    updateTerritory: "/territoryMapping/updateTerritory",
    countTerritory: "/territoryMapping/countTerritory",
    duplicateTerritoryByCity: "/territoryMapping/duplicateTerritoryByCity",
    getTerritory: '/territoryMapping/getTerritory',
    getTerritoryByCode: '/territoryMapping/getTerritoryByCode'
  },
  lead: {
    getLeadsList: "/lead/getLeadsList",
    downloadSample: "/lead/downloadSample",
    uploadLead: "/lead/uploadLead",
    multipleLeadTransfer: "/lead/multipleLeadTransfer",
    getLogsList: "/leadLogs/getLogsList",
  },
  leadInterest: {
    createLeadInterest: "/leadInterest/createLeadInterest",
    leadInterestDetails: "/leadInterest/leadInterestDetails",
    uniqueLeadInterest: "/leadInterest/uniqueLeadInterest",
    interestTransactionalLog: "/leadInterest/interestTransactionalLog",
    getOwnerInterestList: "/leadInterest/getOwnerInterestList",
    getSchoolInterests: "/leadInterest/getSchoolInterests",
    getMultipleSchoolInterests: "/leadInterest/getMultipleSchoolInterests",
    getProductListData: "/leadInterest/getProductList",
    getUserHotsPipeline: "/leadInterest/getUserHotsPipeline",
  },
  manageStageStatus: {
    createStageStatus: "/stageRuleMapping/manageStageStatus",
    getPreviewMap: "/stageRuleMapping/getPreviewMap",
    leadStageStatus: "/checkLeadJourney",
  },
  leadassign: {
    updateLead: "/leadassign/updateLead",
    assignMyLeads: "/leadassign/assignMyLeads",
    updateUUID: "/leadassign/updateUUID",
    updateDndStatus: "/leadassign/updateDndStatus",
    getLeadAssignList: "/leadassign/getLeadAssignList",
    getRelatedToList: "/leadassign/getRelatedToList",
    refurbishLeads: "/leadassign/refurbishLeads",
    changeleadowner: "/leadassign/changeleadowner",
    changeleadInterestowner: "/leadassign/changeleadInterestowner",

  },
  impForm: {
    assignedEngineer: "/implementation/updateAssignedEngineer",
    updateScheduleStatus: '/implementation/updateScheduleStatus'
  },
  config: {
    getConfigDetails: "/config/getConfig",
    getAppVersion: "/config/getAppVersion",
    updateConfigDetails: "/config/updateConfig",
    getServerTime: "/serverTime",
  },
  roleBasedAttendaceMatrix: {
    createRoleBasedAttendaceMatrix:
      "/roleBasedAttendance/createRoleBasedAttendanceMatrix",
    getRoleBasedAttendanceMatrixList:
      "/roleBasedAttendance/getRoleBasedAttendanceMatrixList",
    updateRoleBasedAttendanceMatrixList:
      "/roleBasedAttendance/updateRoleBasedAttendanceMatrixList",
  },
  bdeDetails: {
    getBdeRecentActivityDetails: "/bdeActivities/getBdeRecentActivityDetails",
    createBdeActivity: "/bdeActivities/createBdeActivity",
    getUserActivities: "/bdeActivities/getUserActivities",
    updateBdeActivity: "/activityForm/createActivityForm",
    logBdeActivity: "/activityForm/logBdeActivity",
    updateCollectionTypeBdeActivity: "/bdeActivities/updateBdeActivity"
  },
  alternateContacts: {
    getAlternateContacts: "/alternateContact/getAlternateContactList",
  },
  activityFormMappings: {
    getActivityFormNumber: "/activityFormMapping/getActivityFormNumber",
    getFormToActivity: "/activityFormMapping/getFormToActivity",
    getActivityToActivity: "/activityFormMapping/getActivityToActivity",
    createActivityFormMapping: "/activityFormMapping/createActivityFormMapping",
    createFormMappingProductArray:
      "/activityFormMapping/createFormMappingProductArray",
    getActivityFormMappingList:
      "/activityFormMapping/getActivityFormMappingList",
    updateActivityFormMapping: "/activityFormMapping/updateActivityFormMapping",
    deleteActivityFormMapping: "/activityFormMapping/deleteActivityFormMapping",
    getDependentFields: "/activityFormMapping/getDependentFields",
    getActivityMappingDetails: "/activityFormMapping/getActivityMappingDetails",
    getDetails: "/activityFormMapping/getDetails",
    getHotsField: "/activityFormMapping/getHotsField",
  },
  categories: {
    getCategoriesList: "/category/getCategoryList",
  },
  product: {
    getProductList: "/product/getProductList",
  },
  batch: {
    getBatchList: "/batch/getBatchList",
  },
  freeTrial: {
    getFreeTrialPackageList: "/freeTrial/getFreeTrialPackageList",
  },
  approvalRequest: {
    createRequest: "/approvalRequest/createRequest",
    getRequestList: "/approvalRequest/getRequestList",
    getRequestDetails: "/approvalRequest/getRequestDetails",
    approveReject: "/approvalRequest/approveReject",
    singleCouponRequest: "/couponRequest/singleCouponRequest",
    specialCouponRequest: "/couponRequest/specialCouponRequest",
    reassignRequest: "/approvalRequest/reassignRequest",
    approveClaimRequest: "/approvalRequest/approveClaimRequest",
    getActualSchoolVisits: "/getVisitDetail"
  },
  hierachyDetails: {
    getHierachyDetails: "/hierachy/getHierachyDetails",
    allChildRoles: "/hierachy/all-child-roles",

  },
  gatewayApis: {
    getMasterList: "/gateway/getMasterList",
    addInvoiceCollectionSchedule: '/gateway/addInvoiceCollectionSchedule',
    getScheduleList: '/gateway/getScheduleList',
    getReasonMasterList: '/gateway/getReasonMasterList',
    uploadFileToGcp: "/packages/uploadImageToGCP",
  },
  omsApi: {
    collectPayment: "/api/orderapi/createLeadOnlinePayment/format/json",
  },
  subject: {
    getSubjectList: "/subject/getSubjectList",
    createSubject: "/subject/createSubject",
    getAllSubjects: "/subject/getAllSubjects",
    deleteSubject: "/subject/deleteSubject",
    updateSubject: "/subject/updateSubject",
  },
  customerResponse: {
    getCustomerResponseList: "/customerResponse/getCustomerResponseList",
    getAllCustomerResponses: "/customerResponse/getAllCustomerResponses",
    createCustomerResponse: "/customerResponse/createCustomerResponse",
    updateCustomerResponse: "/customerResponse/updateCustomerResponse",
    deleteCustomerResponse: "/customerResponse/deleteCustomerResponse",
  },
  cubeBdActivity: {
    createCubeBdActivity: "/cubeBdActivity/createCubeBdActivity",
    getCubeBdActivity: "/cubeBdActivity/getCubeBdActivity",
  },
  bdeCollectPayment: {
    createBdeCollectPayment:
      "/bdeCollectPayment/createBdeCollectPaymentActivity",
    paymentCollect: "/bdeCollectPayment/paymentCollect",
  },
  reasonForDisqualification: {
    getReasonForDisqualificationList:
      "/reasonForDisqualification/getReasonForDisqualificationList",
    createReasonForDisqualifiction:
      "/reasonForDisqualification/createReasonForDisqualifiction",
    updateReasonForDisqualification:
      "/reasonForDisqualification/updateReasonForDisqualification",
    deleteReasonForDisqualification:
      "/reasonForDisqualification/deleteReasonForDisqualification",
  },

  bdeActivities: {
    logBdeActivity: "/bdeActivities/logBdeActivity",
    getPendingActivity: "/bdeActivities/getPendingActivity",
    getBdeActivities: "/bdeActivities/getBdeActivities",
    getBdeActivityScore: "/bdeActivities/getBdeActivityScore",
    getBdeActivitiesByRoleName: "/bdeActivities/getBdeActivitiesByRoleName",
    getCurrentMonthActivities: "/bdeActivities/getCurrentMonthActivities",
    closePendingActivities: "/bdeActivities/closePendingActivities",
    checkLeadStageStatus: "/bdeActivities/checkLeadStageStatus",
    logMeetingActivity: "/bdeActivities/logMeetingActivity",
    getBdeActivitiesByDate: "/bdeActivities/fetchBdeActivitiesByDate",
    addActivity: "/bdeActivities/addActivity",
    getCurrentActivities: "/bdeActivities/getCurrentActivities",
    getActivitiesByType: "/bdeActivities/getActivitiesByType",
    getCollectionTypeActivities: "/bdeActivities/getCollectionTypeActivities",
    updateBdeActivity: "/bdeActivities/updateBdeActivity",
  },
  leadDetailsById: {
    leadDetails: "/leadDetails/getLeadDetailsByLeadId",
  },
  leadStageStatus: {
    leadStageStatusDetails: "/leadStageStatus/leadStageStatusDetails",
    checkLead: "/leadStageStatus/checkLead"
  },
  formChangeMasters: {
    getReasonForPaPendingList: "/reasonForPaPending/getReasonForPaPendingList",
    getReasonForPaRejectedList:
      "/reasonForPaRejected/getReasonForPaRejectedList",
    getReasonForObPendingList: "/reasonForObPending/getReasonForObPendingList",
    getReasonForObRejectedList:
      "/reasonForObRejected/getReasonForObRejectedList",
    getReasonForFbPendingList: "/reasonForFbPending/getReasonForFbPendingList",
    getReasonForFbRejectedList:
      "/reasonForFbRejected/getReasonForFbRejectedList",
    getReasonForAckPendingList:
      "/reasonForAckPending/getReasonForAckPendingList",
    getReasonForAckRejectedList:
      "/reasonForAckRejected/getReasonForAckRejectedList",
  },
  claimMaster: {
    getExpenseTypeMapping: "/expenseTypeMapping/getExpenseTypeMapping",
    createClaimMaster: "/claimMaster/createClaimMaster",
    updateClaimMaster: "/claimMaster/updateClaimMaster",
    getClaimMasterDetails: "/claimMaster/getClaimMasterDetails",
    getClaimMasterList: "/claimMaster/getClaimMasterList",
    deleteClaimMaster: "/claimMaster/deleteClaimMaster",
    getAllProductList: "/crmMaster/getAllProductList",
  },
  userClaim: {
    getMyClaimList: "/userClaim/getMyClaimList",
    getUserClaimDetails: "/userClaim/getUserClaimDetails",
    updateUserClaim: "/userClaim/updateClaim",
    createMyClaim: "/userClaim/createMyClaim",
    bulkDelete: "/userClaim/bulkDelete",
    bulkUpdate: "/userClaim/bulkUpdate",
    getUserClaimListBySchool: "/userClaim/getUserClaimListBySchool",
    claimList: '/userClaim/claimList',
    bulkUpdate: '/userClaim/bulkUpdate',
  },
  school: {
    createSchool: "/school/createSchool",
    getSchoolList: "/school/getSchoolList",
    getSchoolDetail: "/school/schoolDetails",
    getSchoolBySchoolCode: "/school/schoolBySchoolCode",
    getAllSchoolList: "/school/getAllSchoolList",
    updateSchool: "/school/updateSchool",
    getSchoolCodeList: "/school/getSchoolCodeList",
    updateContactDetails: "/school/updateContactDetails",
    getBdeActivities: "/school/getBdeActivities",
    getEdcCount: "/school/getEdcCount",
    getBdeActivity: "/school/getBdeActivity",
    getSchoolsByCode: "/school/getSchoolsByCode",
    getSchoolsByCode: "/school/getSchoolsByCode",

  },
  // productMaster: {
  //   getProductMasterList: "/productMaster/getProductMasterList",
  // },
  approvalMapping: {
    createApprovalMapping: "/approvalMapping/createApprovalMapping",
    getApprovalMappingList: "/approvalMapping/getApprovalMappingList",
    getApprovalMappingDetails: "/approvalMapping/getApprovalMappingDetails",
    updateApprovalMapping: "/approvalMapping/updateApprovalMapping",
    getMappingInfo: "/approvalMapping/getMappingInfo",
  },
  crmMaster: {
    createCrmMaster: "/crmMaster/createCrmMaster",
    getCrmMasterList: "/crmMaster/getCrmMasterList",
    deleteCrmMaster: "/crmMaster/deleteCrmMaster",
    updateCrmMaster: "/crmMaster/updateCrmMaster",
    getAllKeyValues: "/crmMaster/getAllKeyValues",
    getAllProductList: "/crmMaster/getAllProductList",
  },
  crmFieldMaster: {
    createCrmFieldMaster: "/crmFieldMaster/createCrmFieldMaster",
    getAllCrmFieldMasterList: "/crmFieldMaster/getAllCrmFieldMasterList",
    updateCrmFieldMaster: "/crmFieldMaster/updateCrmFieldMaster",
    getCrmFieldMasterList: "/crmFieldMaster/getCrmFieldMasterList",
  },
  packages: {
    listHardwareParts: "/packages/listHardwareParts",
    addUpdateHardwarePart: "/packages/addUpdateHardwarePart",
    listHardwareBundle: "/packages/listHardwareBundle",
    addUpdatePartVariants: "/packages/addUpdatePartVariants",
    addUpdateBundleVariants: "/packages/addUpdateBundleVariants",
    packageMasterList: "/packages/packageMasterList",
    listHardwarePartVariants: "/packages/listHardwarePartVariants",
    listHardwareBundleVariants: "/packages/listHardwareBundleVariants",
    masterDataList: "/packages/listPackageMasterData",
    addUpdateHardwareBundle: "/packages/addUpdateHardwareBundle",
    listPackageBundles: "/packages/listPackageBundles",
    listEntityFeatures: "/packages/listEntityFeatures",
    addUpdatePackageBundle: "/packages/addUpdatePackageBundle",
    uploadFileToGcp: "/packages/uploadImageToGCP",
    listReceivingBank: "/packages/listReceivingBank",
    listIssuingBank: "/packages/listIssuingBank",
    listUnitOfMeasurement: "/packages/listUnitOfMeasurement",
    listCampaign: "/packages/listCampaign",
    addUpdateCampaign: "/packages/addUpdateCampaign",
    listSource: "/packages/listSource",
    addUpdateSource: "/packages/addUpdateSource",
    listSubSource: "/packages/listSubSource",
    addUpdateSubSource: "/packages/addUpdateSubSource",
    listHardwareRecommendation: "/packages/listHardwareRecommendation",
    getServiceList: "/packages/listService",
    addUpdateService: "/packages/addUpdateService",
    listPricingMatrix: "/packages/listPricingMatrix",
    addSchoolTdsDetail: "/packages/addSchoolTdsDetail",
    listSchoolTdsDetail: "/packages/listSchoolTdsDetail",
    addUpdatePricingMatrix: "/packages/addUpdatePricingMatrix",
    listMatrixAttributes: "/packages/listMatrixAttributes",
    listVouchers: "/packages/listVouchers",
    listFormInvoices: "/packages/listFormInvoices",
    addUpdateInvoiceDsc: "/packages/addUpdateInvoiceDsc",
    listInvoiceDsc: "/packages/listInvoiceDsc",
    addUpdateHardwareInvoice: "/packages/addUpdateHardwareInvoice",
    listSchoolTdsDetail: "/packages/listSchoolTdsDetail",
    addUpdatePricingMatrix: "/packages/addUpdatePricingMatrix",
    listMatrixAttributes: "/packages/listMatrixAttributes",
    b2bPackageActivation: "/b2bPackageActivation",
    listInvoiceOffice: "/packages/listInvoiceOffice",
    listHardwareInvoice: "/packages/listHardwareInvoice",
    cancelHardwareInvoice: "/packages/cancelHardwareInvoice",
    listSchoolTdsDetail: "/packages/listSchoolTdsDetail",
    addUpdatePricingMatrix: "/packages/addUpdatePricingMatrix",
    listMatrixAttributes: "/packages/listMatrixAttributes",
    b2bPackageActivation: "/b2bPackageActivation",
    packagePriceData: '/packages/packagePriceData',
    packagePriceAttributes: '/packages/packagePriceAttributes',
    listInvoiceCollectionSchedule: '/packages/listInvoiceCollectionSchedule',
    generateInvoiceFromSchedule: '/packages/generateInvoiceFromSchedule',
    listPendingCollection: "/packages/listPendingCollection",
    updateInvoiceDetails: "/packages/updateInvoiceDetails",
    listGeneratedInvoice: "/packages/listGeneratedInvoice",
    listInvoiceIRNErrors: "/packages/listInvoiceIRNErrors",
    listInvoiceScheduleDetails: "/packages/listInvoiceScheduleDetails",
    addVoucher: '/packages/addVoucher',
    voucherDetailsData: '/packages/voucherDetailsData',
    updateVoucherDetail: '/packages/updateVoucherDetail',
    voucherLogDetail: '/packages/voucherLogDetail',
    cancelVoucher: '/packages/cancelVoucher',
    listPendingCollection: "/packages/listPendingCollection",
    pendingCollectionDetail: "/packages/pendingCollectionDetail",
    listSchoolLedger: '/packages/listSchoolLedger',
    schoolLedgerDetails: '/packages/schoolLedgerDetails',
    listHardwareVoucher: '/packages/listHardwareVoucher',
    hwInvoiceCreditDetail: '/packages/hwInvoiceCreditDetail',
    addUpdateHardwareVoucher: '/packages/addUpdateHardwareVoucher',
    listReasonMaster: "/packages/listReasonMaster",
    pendingCollectionDetail: "/packages/pendingCollectionDetail",
    creditDebitAmountLimit: "/packages/creditDebitAmountLimit",
    pendingInvoiceForRelease: "/packages/pendingInvoiceForRelease",
    invoiceProcessAction: "/packages/invoiceProcessAction",
    addUpdateAddendum: "/packages/addUpdateAddendum",
    listSchoolLedgerVoucher: "/packages/listSchoolLedgerVoucher",
    listInvoicedForms: "/packages/listInvoicedForms",
    listHwInvoicedAmountDetails: "/packages/listHwInvoicedAmountDetails"
  },
  purchaseOrder: {
    uploadPurchaseOrderToGCP: "/purchaseOrder/uploadPurchaseOrderToGCP",
    createPurchaseOrder: "/purchaseOrder/createPurchaseOrder",
    getPurchaseOrderList: "/purchaseOrder/getPurchaseOrderList",
    getPurchaseOrderDetails: "/purchaseOrder/getPurchaseOrderDetails",
    getPOListBySchoolCode: "/purchaseOrder/getPOListBySchoolCode",
    updatePurchaseOrderStatus: "/purchaseOrder/updatePurchaseOrderStatus",
    updatePurchaseOrderApprovalStatus: '/purchaseOrder/updatePurchaseOrderApprovalStatus',
  },
  campaignManagment: {
    listPackageBundles: "/packages/listPackageBundles",
    listEntityFeatures: "/packages/listEntityFeatures",
    addUpdatePackageBundle: "/packages/addUpdatePackageBundle",
    uploadFileToGcp: "/packages/uploadImageToGCP",
  },
  quotationConfig: {
    createQuotationConfig: "/quotationConfig/createQuotationConfig",
    getQuotationConfigList: "/quotationConfig/getQuotationConfigList",
    updateQuotationConfig: "/quotationConfig/updateQuotationConfig",
    getQuotationDetails: "/quotation/getQuotationDetails",
    getQuotationListDetail: "/quotationConfig/getQuotationConfigDetail",
  },
  campaignManagment: {
    getCampaignList: "/packages/listCampaign",
    addUpdateCampaign: "/packages/addUpdateCampaign",
  },
  sourceManagment: {
    getSourceList: "/packages/listSource",
    addUpdateSource: "/packages/addUpdateSource",
  },
  subsourceManagment: {
    getSubSourceList: "/packages/listSubSource",
    addUpdateSubSource: "/packages/addUpdateSubSource",
  },
  serviceManagment: {
    getServiceList: "/packages/listService",
    addUpdateService: "/packages/addUpdateService",
  },
  quotation: {
    addQuotation: "/quotation/createQuotation",
    getQuotationList: "/quotation/getQuotationList",
    deleteQuotationList: "/quotation/deleteQuotation",
    getQuotationDetails: "/quotation/getQuotationDetails",
    updateQuotation: "/quotation/updateQuotation",
    getProductSalePriceSum: "/quotation/getProductSalePriceSum",
    updateQuotationApprovalStatus: '/quotation/updateQuotationApprovalStatus',
    getQuotationWithoutPO: "/quotation/getQuotationWithoutPO",
    updateIsPoGenerated: "/quotation/updateIsPoGenerated",
    updateQuotationStatus: "/quotation/updateQuotationStatus"

  },
  implementationForm: {
    implementationCompleteForm: "/implementation/completeForm",
    fetchImplementationList: "/implementation/getImplementationList",
    fetchImplementationListByApprovalStatus: "/implementation/getImplementationListByApprovalStatus",
    createProductField: "/implementation/createProductField",
    getProductField: "/implementation/getProductField",
    getActivatedImplementationList: "/implementation/getActivatedImplementationList",
    updateImplementationByStatus: "/implementation/updateStatus",
    b2bPackageActivation: "/b2bPackageActivation",
    updateActivationPackage: "/implementation/updateActivationPackage",
    updateScheduleStatus: "/implementation/updateScheduleStatus",
    listBatchDetails: "/packages/listBatchDetails",
    updateHardwareDetails: "/implementation/updateHardwareDetails",
    getImplementationByCondition: '/implementation/getImplementationByCondition',
    uploadQcImageToGcp: '/implementationQc/uploadQcImageToGcp',
    createQc: '/implementationQc/createQc',
    getPrevQcFormData: '/implementationQc/getPrevQcFormData',
    getQcList: '/implementationQc/getQcList',
    getImplementationListWithEr: '/implementation/getImplementationListWithEr',
    getAssignedTaskList: '/implementationEngineer/myAssignedTaskList',
    updateActivity: '/bdeActivities/updateActivity'
  },
  activatedPackage: {
    listActivatedSchool: "/packages/listActivatedSchool",
    listActivatedPackageDetails: "/packages/listActivatedPackageDetails",
    activatedPackageDetails: "/packages/activatedPackageDetails",
    updateActivatedPackageDetails: "/packages/updateActivatedPackageDetails",
    updatePackageActivationStatus: "/packages/updatePackageActivationStatus"
  },
  approvalMatrix: {
    createApprovalMatrix: "/approvalMatrix/createApprovalMatrix",
    getApprovalMatrixList: "/approvalMatrix/getApprovalMatrixList",
    updateApprovalMatrix: "/approvalMatrix/updateApprovalMatrix",
  },
  salesApproval: {
    getSalesApprovalList: '/salesApproval/getSalesApprovalList',
    getSalesApprovalListAll: '/salesApproval/getSalesApprovalListAll',
    acceptApprovalRequest: '/salesApproval/acceptApprovalRequest',
    rejectApprovalRequest: '/salesApproval/rejectApprovalRequest',
    assignApprovalRequest: "/salesApproval/assignApprovalRequest",
  },
  alertNotification: {
    getAlertNotification: '/alertNotification/getAlertNotification',
    createAlertNotification: '/alertNotification/createAlertNotification',
    updateAlertNotificationStatus: '/alertNotification/updateAlertNotificationStatus'
  },
  tds: {
    uploadTds: '/tds/uploadTdsToGcp',
  },
  dsc: {
    uploadDsc: '/dsc/uploadDscToGCP',
  },
  implementationSiteSurvey: {
    createSiteSurvey: '/implementationSiteSurvey/createSiteSurvey',
    getSiteSurveyList: '/implementationSiteSurvey/getSiteSurveyList',
    getSiteSurveyDetails: '/implementationSiteSurvey/getSiteSurveyDetails',
    getPrevSsrFormData: '/implementationSiteSurvey/getPrevSsrFormData',
    updateApprovalStatus: '/implementationSiteSurvey/updateSsrApprovalStatus'
  },
  paymentManagement: {
    listCollectionDetails: '/packages/listCollectionDetails',
    listPendingCollection: '/packages/listPendingCollection',
    approvePaymentFinance: '/packages/approvePaymentFinance',
    updateAdjustmentStatus: '/packages/updateAdjustmentStatus',
    rejectPaymentDepositCases: '/packages/rejectPaymentFinance',
    pendingCollectionDetail: '/packages/pendingCollectionDetail',
    getPaymentDepositCases: '/packages/listPaymentDetailsFinance',
    addUpdateSchoolPayment: '/packages/addUpdateSchoolPayment',
    listPaymentApprovalDetails: '/packages/listPaymentApprovalDetails',
    uploadCollectionEvidence: '/collection/uploadCollectionEvidence',
    listRejectedPayment: '/packages/listRejectedPayment',
    listReceivingBank: '/packages/listReceivingBank',
    listAddendumDetail: '/packages/listAddendumDetail',
    uploadAddendumProof: '/collection/uploadAddendumProof'
  }
};
