const DatasetNames = {
    OnlineLeads: "OnlineLeads63c63d31883484001231014e",
    Leadassigns: "Leadassigns",
    Schools: "Schools",
    Leads: "Leads",
    EmployeeClaim: 'EmployeeClaim',
    Approvalmappings: 'Approvalmappings',
    ApprovalRequest: 'Approvalrequests',
    LeadActivity: "LeadActivities",
    Bdeactivities: "Bdeactivities",
    Attendances: "Attendances",
    Activities: "Activities",
    Rolebasedattendanceactivitymodels: "Rolebasedattendanceactivitymodels",
    EmployeeLeadsOrder: "EmployeeLeadsOrder",
    TblUserfreetrial: "TblUserfreetrial",
    Leadinterests: "Leadinterests",
    CountryCityStateMapping: "CountryCityStateMapping",
    LeadStageStatus: "Leadstagestatuses",
    LearningProfileMaster: "LearningProfileMaster",
    LeadassignsBq: "Leadassigns",
    BdeactivitiesBq: "Bdeactivities",
    LeadStageStatusBq: "Leadstagestatuses",
    LeadinterestsBq: "Leadinterests",
    RolebasedattendanceactivitymodelsBq: 'Rolebasedattendanceactivitymodels',
    ActivitiesBq: 'Activities',
    OMSOrders: 'OMSEmployeeOrder63c78d1d88348400123104d0',
    EmployeeLeadsOrderBq: "EmployeeLeadsOrder",
    Targets: "Targets",
    Territorymappings: "Territorymappings",
    UserClaim: 'Userclaims',
    TblEmployee: 'TblEmployee',
    Purchaseorders: "Purchaseorders",
    Quotations: "Quotations",
    Implementationforms: "Implementationforms",
    SyllabusMappingMaster: "SyllabusMappingMaster",
    SyllabusBoardClassMaster: "SyllabusBoardClassMaster",
    Leadowners: "Leadowners",
    Ledger:"Ledger"
}

const CubeDataset = {
    OnlineLeads: {
        uuid: `${DatasetNames.OnlineLeads}.uuid`,
        parentId: `${DatasetNames.OnlineLeads}.parentId`,
        displayName: `${DatasetNames.OnlineLeads}.displayName`,
        username: `${DatasetNames.OnlineLeads}.username`,
        city: `${DatasetNames.OnlineLeads}.city`,
        mobile: `${DatasetNames.OnlineLeads}.mobile`,
        phone: `${DatasetNames.OnlineLeads}.phone`,
        countryName: `${DatasetNames.OnlineLeads}.countryName`,
        stateName: `${DatasetNames.OnlineLeads}.stateName`,
        stateCode: `${DatasetNames.OnlineLeads}.stateCode`,
        age: `${DatasetNames.OnlineLeads}.age`,
        schoolName: `${DatasetNames.OnlineLeads}.schoolName`,
        platform: `${DatasetNames.OnlineLeads}.platform`,
        email: `${DatasetNames.OnlineLeads}.email`,
        userType: `${DatasetNames.OnlineLeads}.ubviV1674125054656`,
        createdOn: `${DatasetNames.OnlineLeads}.createdOn`,
        createTime: `${DatasetNames.OnlineLeads}.createTime`,
        updatedOn: `${DatasetNames.OnlineLeads}.updatedOn`,

    },
    EmployeeClaim: {
        claimId: `${DatasetNames.EmployeeClaim}.claimId`,
        MongoID: `${DatasetNames.EmployeeClaim}.MongoID`,
        requestByName: `${DatasetNames.EmployeeClaim}.requestByName`,
        requestByEmpCode: `${DatasetNames.EmployeeClaim}.requestByEmpCode`,
        visitNumber: `${DatasetNames.EmployeeClaim}.visitNumber`,
        visitDate: `${DatasetNames.EmployeeClaim}.visitDate`,
        billFile: `${DatasetNames.EmployeeClaim}.billFile`,
        schoolName: `${DatasetNames.EmployeeClaim}.schoolName`,
        expenseType: `${DatasetNames.EmployeeClaim}.expenseType`,
        claimStatus: `${DatasetNames.EmployeeClaim}.claimStatus`,
        approvedDate: `${DatasetNames.EmployeeClaim}.approvedDate`,
        approvedAmount: `${DatasetNames.EmployeeClaim}.approvedAmount`,
        claimAmount: `${DatasetNames.EmployeeClaim}.claimAmount`,
        // createdAt: `${DatasetNames.EmployeeClaim}.createdAt`,
        // updatedAt: `${DatasetNames.EmployeeClaim}.updatedAt`,
        TotalApprovedAmount: `${DatasetNames.EmployeeClaim}.TotalApprovedAmount`,
        totalRecords: `${DatasetNames.EmployeeClaim}.totalRecords`,
        TotalRejectedAmount: `${DatasetNames.EmployeeClaim}.TotalRejectedAmount`,
        TotalPendingAmount: `${DatasetNames.EmployeeClaim}.TotalPendingAmount`,
        TotalClaimAmount: `${DatasetNames.EmployeeClaim}.TotalClaimAmount`,
        cityName: `${DatasetNames.EmployeeClaim}.cityName`,
        stateName: `${DatasetNames.EmployeeClaim}.stateName`,
        requestByRoleName: `${DatasetNames.EmployeeClaim}.requestByRoleName`,
        createdAt: `${DatasetNames.EmployeeClaim}.Createdatuserclaims`,
        updatedAt: `${DatasetNames.EmployeeClaim}.Updatedatuserclaims`
    },
    UserClaim: {
        claimId: `${DatasetNames.UserClaim}.claimId`,
        MongoID: `${DatasetNames.UserClaim}.MongoID`,
        requestByName: `${DatasetNames.UserClaim}.requestByName`,
        requestByEmpCode: `${DatasetNames.UserClaim}.requestByEmpCode`,
        visitNumber: `${DatasetNames.UserClaim}.visitNumber`,
        visitDate: `${DatasetNames.UserClaim}.visitDate`,
        billFile: `${DatasetNames.UserClaim}.billFile`,
        schoolName: `${DatasetNames.UserClaim}.schoolName`,
        expenseType: `${DatasetNames.UserClaim}.expenseType`,
        claimStatus: `${DatasetNames.UserClaim}.claimStatus`,
        approvedDate: `${DatasetNames.UserClaim}.approvedDate`,
        approvedAmount: `${DatasetNames.UserClaim}.approvedAmount`,
        claimAmount: `${DatasetNames.UserClaim}.claimAmount`,
        createdAt: `${DatasetNames.UserClaim}.createdAt`,
        updatedAt: `${DatasetNames.UserClaim}.updatedAt`,
        TotalApprovedAmount: `${DatasetNames.UserClaim}.TotalApprovedAmount`,
        totalRecords: `${DatasetNames.UserClaim}.totalRecords`,
        TotalRejectedAmount: `${DatasetNames.UserClaim}.TotalRejectedAmount`,
        TotalPendingAmount: `${DatasetNames.UserClaim}.TotalPendingAmount`,
        TotalClaimAmount: `${DatasetNames.UserClaim}.TotalClaimAmount`,
        cityName: `${DatasetNames.UserClaim}.cityName`,
        stateName: `${DatasetNames.UserClaim}.stateName`,
        requestByRoleName: `${DatasetNames.UserClaim}.requestByRoleName`,
        schoolCode: `${DatasetNames.UserClaim}.schoolCode`,
        visitPurpose: `${DatasetNames.UserClaim}.visitPurpose`,
        unitLabel: `${DatasetNames.UserClaim}.unitLabel`,
        unit: `${DatasetNames.UserClaim}.unit`,
        claimRemarks: `${DatasetNames.UserClaim}.claimRemarks`,
        visitTimeIn: `${DatasetNames.UserClaim}.visitTimeIn`,
        visitTimeOut: `${DatasetNames.UserClaim}.visitTimeOut`,

    },
    TblEmployee: {
        name: `${DatasetNames.TblEmployee}.eName`,
        eCode: `${DatasetNames.TblEmployee}.eCode`,
        stateName: `${DatasetNames.TblEmployee}.eStateName`,
        cityName: `${DatasetNames.TblEmployee}.eCityName`,
        roleName: `${DatasetNames.TblEmployee}.roleName`,
        profileName: `${DatasetNames.TblEmployee}.profileName`,

    },

    Schools: {
        address: `${DatasetNames.Schools}.address`,
        interestShown: `${DatasetNames.Schools}.interestShown`,
        leadId: `${DatasetNames.Schools}.leadId`,
        schoolCode: `${DatasetNames.Schools}.schoolCode`,
        schoolName: `${DatasetNames.Schools}.schoolName`,
        createdAt: `${DatasetNames.Schools}.createdAt`,
        updatedAt: `${DatasetNames.Schools}.updatedAt`,
        assignedToDisplayName: `${DatasetNames.Schools}.assignedToDisplayName`,
        assignedToRoleName: `${DatasetNames.Schools}.assignedToRoleName`,
        city:`${DatasetNames.Schools}.city`

    },
    Approvalmappings: {
        Id: `${DatasetNames.Approvalmappings}.Id`,
        approvalType: `${DatasetNames.Approvalmappings}.approvalType`,
        approverProfile: `${DatasetNames.Approvalmappings}.approverProfile`,
        modifiedBy: `${DatasetNames.Approvalmappings}.modifiedBy`,
        createdAt: `${DatasetNames.Approvalmappings}.createdAt`,
        updatedAt: `${DatasetNames.Approvalmappings}.updatedAt`
    },
    ApprovalRequest: {
        requestNumber: `${DatasetNames.ApprovalRequest}.requestNumber`,
        _id: `${DatasetNames.ApprovalRequest}.MongoID`,
        requestId: `${DatasetNames.ApprovalRequest}.requestId`,
        requestByName: `${DatasetNames.ApprovalRequest}.requestByName`,
        shortDescription: `${DatasetNames.ApprovalRequest}.shortDescription`,
        approverName: `${DatasetNames.ApprovalRequest}.approverName`,
        requestType: `${DatasetNames.ApprovalRequest}.requestType`,
        requestStatus: `${DatasetNames.ApprovalRequest}.requestStatus`,
        requestByEmpCode: `${DatasetNames.ApprovalRequest}.requestByEmpCode`,
        createdAt: `${DatasetNames.ApprovalRequest}.createdAt`,
        updatedAt: `${DatasetNames.ApprovalRequest}.updatedAt`,
        approverRoleName: `${DatasetNames.ApprovalRequest}.approverRoleName`,
        approverEmpCode: `${DatasetNames.ApprovalRequest}.approverEmpCode`,
        totalRecords: `${DatasetNames.ApprovalRequest}.totalRecords`,
    },
    Leadassigns: {
        Id: `${DatasetNames.Leadassigns}.Id`,
        leadId: `${DatasetNames.Leadassigns}.leadId`,
        name: `${DatasetNames.Leadassigns}.name`,
        mobile: `${DatasetNames.Leadassigns}.mobile`,
        email: `${DatasetNames.Leadassigns}.email`,
        city: `${DatasetNames.Leadassigns}.city`,
        state: `${DatasetNames.Leadassigns}.state`,
        userType: `${DatasetNames.Leadassigns}.userType`,
        type: `${DatasetNames.Leadassigns}.type`,
        assignedToDisplayName: `${DatasetNames.Leadassigns}.assignedToDisplayName`,
        assignedToRoleName: `${DatasetNames.Leadassigns}.assignedToRoleName`,
        createdAt: `${DatasetNames.Leadassigns}.createdAt`,
        updatedAt: `${DatasetNames.Leadassigns}.updatedAt`,
        registrationDate: `${DatasetNames.Leadassigns}.registrationDate`,
        sourceName: `${DatasetNames.Leadassigns}.sourceName`,
        subSourceName: `${DatasetNames.Leadassigns}.subSourceName`,
        campaignId: `${DatasetNames.Leadassigns}.campaignId`,
        count: `${DatasetNames.Leadassigns}.count`,
        board: `${DatasetNames.Leadassigns}.board`,
        class: `${DatasetNames.Leadassigns}.class`,
        campaignId: `${DatasetNames.Leadassigns}.campaignId`,
        stageName: `${DatasetNames.Leadassigns}.stageName`,
        statusName: `${DatasetNames.Leadassigns}.statusName`,
        dndStatus: `${DatasetNames.Leadassigns}.dndStatus`,
        isRefurbished: `${DatasetNames.Leadassigns}.isRefurbished`

    },
    OMSOrders: {
        punched: `${DatasetNames.OMSOrders}.AjiVN1678695366158`,
        netOfInvoice: `${DatasetNames.OMSOrders}.QsvGq1678695547908`,
        orderId: `${DatasetNames.OMSOrders}.oId`,
        eEmpid: `${DatasetNames.OMSOrders}.eEmpid`,
        eName: `${DatasetNames.OMSOrders}.eName`,
        lUuid: `${DatasetNames.OMSOrders}.lUuid`,
        orderStatus: `${DatasetNames.OMSOrders}.oOrderstatus`,
        Createdon: `${DatasetNames.OMSOrders}.oOrderdate`,
        updatedOn: `${DatasetNames.OMSOrders}.oUpdatedate`,
        count: `${DatasetNames.OMSOrders}.count`,
        totalOrder: `${DatasetNames.OMSOrders}.Idzvh1679551040313`
    },
    Leads: {
        name: `${DatasetNames.Leads}.name`,
        Id: `${DatasetNames.Leads}.Id`,
        createdAt: `${DatasetNames.Leads}.createdAt`,
        userType: `${DatasetNames.Leads}.userType`,
        city: `${DatasetNames.Leads}.city`,
        mobile: `${DatasetNames.Leads}.mobile`,
        sourceName: `${DatasetNames.Leads}.sourceName`,
        subSourceName: `${DatasetNames.Leads}.subSourceName`,
        updatedAt: `${DatasetNames.Leads}.updatedAt`,
        userType: `${DatasetNames.Leads}.userType`,
        board: `${DatasetNames.Leads}.board`,
        email: `${DatasetNames.Leads}.email`,
        countryCode: `${DatasetNames.Leads}.countryCode`,
        state: `${DatasetNames.Leads}.state`,
        assignedToRoleName: `${DatasetNames.Leads}.assignedToRoleName`,
        count: `${DatasetNames.Leads}.count`
    },
    LeadActivity: {
        LeadScore: `${DatasetNames.LeadActivity}.LeadScore`,
        userId: `${DatasetNames.LeadActivity}.userId`
    },
    Bdeactivities: {
        activityName: `${DatasetNames.Bdeactivities}.activityName`,
        customerResponse: `${DatasetNames.Bdeactivities}.customerResponse`,
        conversationWith: `${DatasetNames.Bdeactivities}.conversationWith`,
        callDuration: `${DatasetNames.Bdeactivities}.callDuration`,
        callRecording: `${DatasetNames.Bdeactivities}.callRecording`,
        callStatus: `${DatasetNames.Bdeactivities}.callStatus`,
        reasonForDQ: `${DatasetNames.Bdeactivities}.reasonForDQ`,
        interestedIn: `${DatasetNames.Bdeactivities}.interestedIn`,
        name: `${DatasetNames.Bdeactivities}.name`,
        comments: `${DatasetNames.Bdeactivities}.comments`,
        startDateTime: `${DatasetNames.Bdeactivities}.startDateTime`,
        endDateTime: `${DatasetNames.Bdeactivities}.endDateTime`,
        createdBy: `${DatasetNames.Bdeactivities}.createdBy`,
        createdByName: `${DatasetNames.Bdeactivities}.createdByName`,
        createdByProfileName: `${DatasetNames.Bdeactivities}.createdByProfileName`,
        paymentUrl: `${DatasetNames.Bdeactivities}.paymentUrl`,
        paymentAmount: `${DatasetNames.Bdeactivities}.paymentAmount`,
        createdAt: `${DatasetNames.Bdeactivities}.createdAt`,
        subject: `${DatasetNames.Bdeactivities}.subject`,
        category: `${DatasetNames.Bdeactivities}.category`,
        leadId: `${DatasetNames.Bdeactivities}.leadId`,
        Id: `${DatasetNames.Bdeactivities}.Id`,
        createdBy: `${DatasetNames.Bdeactivities}.createdBy`,
        activityId: `${DatasetNames.Bdeactivities}.activityId`,
        activityScore: `${DatasetNames.Bdeactivities}.activityScore`,
        status: `${DatasetNames.Bdeactivities}.status`,
        totalActivityScore: `${DatasetNames.BdeactivitiesBq}.TotalActivityScore`,
        buAverage: `${DatasetNames.BdeactivitiesBq}.BUAverage`,
        count: `${DatasetNames.BdeactivitiesBq}.count`,
        nationalAverage: `${DatasetNames.BdeactivitiesBq}.NationalAverage`,
        taskActivity: `${DatasetNames.Bdeactivities}.taskActivity`,
        createdByRoleName: `${DatasetNames.Bdeactivities}.createdByRoleName`,
        knownLanguages: `${DatasetNames.Bdeactivities}.knownLanguages`,
        UniqueSchools: `${DatasetNames.Bdeactivities}.UniqueSchools`,
        totalRecords: `${DatasetNames.Bdeactivities}.totalRecords`,
        TotalCV: `${DatasetNames.Bdeactivities}.TotalCV`,
        learningProfileGroupCode: `${DatasetNames.Bdeactivities}.learningProfileGroupCode`,
        PriorityNew: `${DatasetNames.Bdeactivities}.PriorityNew`,
        raisedClaim: `${DatasetNames.Bdeactivities}.raisedClaim`,
    },
    Attendances: {
        attendanceMatrixType: `${DatasetNames.Attendances}.attendanceMatrixType`,
        maxTarget: `${DatasetNames.Attendances}.maxTarget`,
        minTarget: `${DatasetNames.Attendances}.minTarget`,
        updatedAt: `${DatasetNames.Attendances}.updatedAt`,
        status: `${DatasetNames.Attendances}.status`,
        attendanceMatrixType: `${DatasetNames.Attendances}.attendanceMatrixType`,
        profileName: `${DatasetNames.Attendances}.profileName`,
        roleName: `${DatasetNames.Attendances}.roleName`
    },
    Activities: {
        Id: `${DatasetNames.Activities}.id`,
        name: `${DatasetNames.Activities}.activityName`,
        maxScore: `${DatasetNames.Activities}.maxScore`,
        userType: `${DatasetNames.Activities}.userType`,
        status: `${DatasetNames.ActivitiesBq}.status`,
        isDeleted: `${DatasetNames.ActivitiesBq}.isDeleted`,
    },
    ActivitiesBq: {
        Id: `${DatasetNames.ActivitiesBq}.id`,
        name: `${DatasetNames.Activities}.activityName`,
        maxScore: `${DatasetNames.ActivitiesBq}.maxScore`,
        userType: `${DatasetNames.ActivitiesBq}.userType`,
        status: `${DatasetNames.ActivitiesBq}.status`,
        isDeleted: `${DatasetNames.ActivitiesBq}.isDeleted`,
    },
    Rolebasedattendanceactivitymodels: {
        activityName: `${DatasetNames.Rolebasedattendanceactivitymodels}.activityName`,
        dailyTarget: `${DatasetNames.Rolebasedattendanceactivitymodels}.dailyTarget`,
        weeklyTarget: `${DatasetNames.Rolebasedattendanceactivitymodels}.weeklyTarget`,
        monthlyTarget: `${DatasetNames.Rolebasedattendanceactivitymodels}.monthlyTarget`,
        activityId: `${DatasetNames.Rolebasedattendanceactivitymodels}.activityId`,
        status: `${DatasetNames.Rolebasedattendanceactivitymodels}.status`,
        roleName: `${DatasetNames.Rolebasedattendanceactivitymodels}.roleName`,
        updatedAt: `${DatasetNames.Rolebasedattendanceactivitymodels}.updatedAt`,
        profileName: `${DatasetNames.Rolebasedattendanceactivitymodels}.profileName`,
    },
    RolebasedattendanceactivitymodelsBq: {
        activityName: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.activityName`,
        dailyTarget: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.dailyTarget`,
        weeklyTarget: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.weeklyTarget`,
        monthlyTarget: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.monthlyTarget`,
        activityId: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.activityId`,
        status: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.status`,
        roleName: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.roleName`,
        updatedAt: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.updatedAt`,
        profileName: `${DatasetNames.RolebasedattendanceactivitymodelsBq}.profileName`,
    },
    EmployeeLeadsOrder: {
        eName: `${DatasetNames.EmployeeLeadsOrder}.eName`,
        lUuid: `${DatasetNames.EmployeeLeadsOrder}.lUuid`,
        Ordno: `${DatasetNames.EmployeeLeadsOrder}.oOrdno`,
        orderId: `${DatasetNames.EmployeeLeadsOrder}.oId`,
        Orderdate: `${DatasetNames.EmployeeLeadsOrder}.oOrderdate`,
        Actualorderstatus: `${DatasetNames.EmployeeLeadsOrder}.oActualorderstatus`,
        orderStatus: `${DatasetNames.EmployeeLeadsOrder}.oOrderstatus`,
        Createdon: `${DatasetNames.EmployeeLeadsOrder}.oOrderdate`,
        updatedOn: `${DatasetNames.EmployeeLeadsOrder}.oUpdatedate`,
        netOfInvoice: `${DatasetNames.EmployeeLeadsOrder}.NetOfInvoice`,
        realised: `${DatasetNames.EmployeeLeadsOrder}.Realised_Amount_ofwuC1679569421369`,
        punched: `${DatasetNames.EmployeeLeadsOrder}.Punched`,
        eEmpid: `${DatasetNames.EmployeeLeadsOrder}.eEmpid`,
        orderTotalAmount: `${DatasetNames.EmployeeLeadsOrder}.oTotalamt`,
        eCreatedOn: `${DatasetNames.EmployeeLeadsOrder}.eCreatedon`,
        lStudentName: `${DatasetNames.EmployeeLeadsOrder}.lStudentname`,
        count: `${DatasetNames.EmployeeLeadsOrder}.count`,
        totalOrder: `${DatasetNames.EmployeeLeadsOrder}.SLTPw1677842104696`
    },
    EmployeeLeadsOrderBq: {
        eName: `${DatasetNames.EmployeeLeadsOrderBq}.eName`,
        lUuid: `${DatasetNames.EmployeeLeadsOrderBq}.lUuid`,
        Ordno: `${DatasetNames.EmployeeLeadsOrderBq}.oOrdno`,
        orderId: `${DatasetNames.EmployeeLeadsOrderBq}.oId`,
        Orderdate: `${DatasetNames.EmployeeLeadsOrderBq}.oOrderdate`,
        Actualorderstatus: `${DatasetNames.EmployeeLeadsOrderBq}.oActualorderstatus`,
        orderStatus: `${DatasetNames.EmployeeLeadsOrderBq}.oOrderstatus`,
        Createdon: `${DatasetNames.EmployeeLeadsOrderBq}.oOrderdate`,
        updatedOn: `${DatasetNames.EmployeeLeadsOrderBq}.oUpdatedate`,
        netOfInvoice: `${DatasetNames.EmployeeLeadsOrderBq}.NetOfInvoice`,
        //olPriceSum:`${DatasetNames.EmployeeLeadsOrder}.QPsWV1670319354012`,
        //ofPriceSum:`${DatasetNames.EmployeeLeadsOrder}.aFwCV1670319291881`,
        realised: `${DatasetNames.EmployeeLeadsOrderBq}.Realised_Amount_ofwuC1679569421369`,
        punched: `${DatasetNames.EmployeeLeadsOrderBq}.Punched`,
        eEmpid: `${DatasetNames.EmployeeLeadsOrderBq}.eEmpid`,
        orderTotalAmount: `${DatasetNames.EmployeeLeadsOrderBq}.oTotalamt`,
        eCreatedOn: `${DatasetNames.EmployeeLeadsOrderBq}.eCreatedon`,
        lStudentName: `${DatasetNames.EmployeeLeadsOrderBq}.lStudentname`,
        count: `${DatasetNames.EmployeeLeadsOrderBq}.count`,
        totalOrder: `${DatasetNames.EmployeeLeadsOrderBq}.SLTPw1677842104696`,
    },
    TblUserfreetrial: {
        utfProductname: `${DatasetNames.TblUserfreetrial}.utfProductname`,
        createdon: `${DatasetNames.TblUserfreetrial}.createdon`,
        utfExpiryDate: `${DatasetNames.TblUserfreetrial}.utfExpiryDate`,
        uftUuid: `${DatasetNames.TblUserfreetrial}.uftUuid`,
    },
    Leadinterests: {
        Id: `${DatasetNames.Leadinterests}.Id`,
        leadId: `${DatasetNames.Leadinterests}.leadId`,
        learningProfile: `${DatasetNames.Leadinterests}.learningProfile`,
        stageName: `${DatasetNames.Leadinterests}.stageName`,
        sourceName: `${DatasetNames.Leadinterests}.sourceName`,
        subSourceName: `${DatasetNames.Leadinterests}.subSourceName`,
        assignedToDisplayName: `${DatasetNames.Leadinterests}.assignedToDisplayName`,
        schoolId: `${DatasetNames.Leadinterests}.schoolId`,
        school: `${DatasetNames.Leadinterests}.school`,
        board: `${DatasetNames.Leadinterests}.board`,
        class: `${DatasetNames.Leadinterests}.class`,
        campaignName: `${DatasetNames.Leadinterests}.campaignName`,
        updatedAt: `${DatasetNames.Leadinterests}.updatedAt`,
        createdAt: `${DatasetNames.Leadinterests}.createdAt`,
        edc: `${DatasetNames.Leadinterests}.edc`,
        softwareContractValue: `${DatasetNames.Leadinterests}.softwareContractValue`,
        edcCount: `${DatasetNames.Leadinterests}.edcCount`,
        statusName: `${DatasetNames.Leadinterests}.statusName`,
        priority: `${DatasetNames.Leadinterests}.priority`,
        learningProfileGroupName: `${DatasetNames.Leadinterests}.learningProfileGroupName`,
        MaxEdc: `${DatasetNames.Leadinterests}.MaxEdc`,
        EdcCountSum: `${DatasetNames.Leadinterests}.EdcCountSum`,
        LearningProfileGroupedName: `${DatasetNames.Leadinterests}.LearningProfileGroupedName`,

    },
    CountryCityStateMapping: {
        countryCode: `${DatasetNames.CountryCityStateMapping}.countryCode`,
        stateName: `${DatasetNames.CountryCityStateMapping}.stateName`,
        cityName: `${DatasetNames.CountryCityStateMapping}.cityName`,
        stateCode: `${DatasetNames.CountryCityStateMapping}.stateCode`,
        cityCode: `${DatasetNames.CountryCityStateMapping}.cityCode`,
        countryName: `${DatasetNames.CountryCityStateMapping}.countryName`,
        countryId: `${DatasetNames.CountryCityStateMapping}.countryId`,
        stateId: `${DatasetNames.CountryCityStateMapping}.stateId`,
        cityId: `${DatasetNames.CountryCityStateMapping}.cityId`,
        territoryName: `${DatasetNames.CountryCityStateMapping}.territoryName`,
        territoryId: `${DatasetNames.CountryCityStateMapping}.territoryId`,
        territoryCode: `${DatasetNames.CountryCityStateMapping}.territoryCode`,
    },
    LeadStageStatus: {
        createdAt: `${DatasetNames.LeadStageStatus}.createdAt`,
        stageName: `${DatasetNames.LeadStageStatus}.stageName`,
        leadId: `${DatasetNames.LeadStageStatus}.leadId`
    },
    LearningProfileMaster: {
        profileName: `${DatasetNames.LearningProfileMaster}.profileName`,
        userTypeId: `${DatasetNames.LearningProfileMaster}.userTypeId`
    },
    LeadassignsBq: {
        Id: `${DatasetNames.LeadassignsBq}.MongoID`,
        leadId: `${DatasetNames.LeadassignsBq}.leadId`,
        name: `${DatasetNames.LeadassignsBq}.name`,
        mobile: `${DatasetNames.LeadassignsBq}.mobile`,
        email: `${DatasetNames.LeadassignsBq}.email`,
        city: `${DatasetNames.LeadassignsBq}.city`,
        state: `${DatasetNames.LeadassignsBq}.state`,
        userType: `${DatasetNames.LeadassignsBq}.userType`,
        type: `${DatasetNames.LeadassignsBq}.type`,
        assignedToDisplayName: `${DatasetNames.LeadassignsBq}.assignedToDisplayName`,
        assignedToRoleName: `${DatasetNames.LeadassignsBq}.assignedToRoleName`,
        createdAt: `${DatasetNames.LeadassignsBq}.createdAt`,
        updatedAt: `${DatasetNames.LeadassignsBq}.updatedAt`,
        registrationDate: `${DatasetNames.LeadassignsBq}.registrationDate`,
        sourceName: `${DatasetNames.LeadassignsBq}.sourceName`,
        subSourceName: `${DatasetNames.LeadassignsBq}.subSourceName`,
        campaignId: `${DatasetNames.LeadassignsBq}.campaignId`,
        count: `${DatasetNames.LeadassignsBq}.count`,
        board: `${DatasetNames.LeadassignsBq}.board`,
        class: `${DatasetNames.LeadassignsBq}.class`,
        campaignId: `${DatasetNames.LeadassignsBq}.campaignId`,
        stageName: `${DatasetNames.LeadassignsBq}.stageName`,
        statusName: `${DatasetNames.LeadassignsBq}.statusName`,
        dndStatus: `${DatasetNames.LeadassignsBq}.dndStatus`
    },
    LeadStageStatusBq: {
        createdAt: `${DatasetNames.LeadStageStatusBq}.createdAt`,
        stageName: `${DatasetNames.LeadStageStatusBq}.stageName`,
        leadId: `${DatasetNames.LeadStageStatusBq}.leadId`
    },
    LeadinterestsBq: {
        Id: `${DatasetNames.LeadinterestsBq}.Id`,
        leadId: `${DatasetNames.LeadinterestsBq}.leadId`,
        learningProfile: `${DatasetNames.LeadinterestsBq}.learningProfile`,
        sourceName: `${DatasetNames.LeadinterestsBq}.sourceName`,
        subSourceName: `${DatasetNames.LeadinterestsBq}.subSourceName`,
        school: `${DatasetNames.LeadinterestsBq}.school`,
        board: `${DatasetNames.LeadinterestsBq}.board`,
        class: `${DatasetNames.LeadinterestsBq}.class`,
        campaignName: `${DatasetNames.LeadinterestsBq}.campaignName`,
        updatedAt: `${DatasetNames.LeadinterestsBq}.updatedAt`,
        createdAt: `${DatasetNames.LeadinterestsBq}.createdAt`,
    },
    BdeactivitiesBq: {
        activityName: `${DatasetNames.BdeactivitiesBq}.activityName`,
        customerResponse: `${DatasetNames.BdeactivitiesBq}.customerResponse`,
        conversationWith: `${DatasetNames.BdeactivitiesBq}.conversationWith`,
        callDuration: `${DatasetNames.BdeactivitiesBq}.callDuration`,
        callRecording: `${DatasetNames.BdeactivitiesBq}.callRecording`,
        callStatus: `${DatasetNames.BdeactivitiesBq}.callStatus`,
        reasonForDQ: `${DatasetNames.BdeactivitiesBq}.reasonForDQ`,
        interestedIn: `${DatasetNames.BdeactivitiesBq}.interestedIn`,
        name: `${DatasetNames.BdeactivitiesBq}.name`,
        comments: `${DatasetNames.BdeactivitiesBq}.comments`,
        startDateTime: `${DatasetNames.BdeactivitiesBq}.startDateTime`,
        endDateTime: `${DatasetNames.BdeactivitiesBq}.endDateTime`,
        createdBy: `${DatasetNames.BdeactivitiesBq}.createdBy`,
        createdByName: `${DatasetNames.BdeactivitiesBq}.createdByName`,
        createdByProfileName: `${DatasetNames.BdeactivitiesBq}.createdByProfileName`,
        paymentUrl: `${DatasetNames.BdeactivitiesBq}.paymentUrl`,
        paymentAmount: `${DatasetNames.BdeactivitiesBq}.paymentAmount`,
        createdAt: `${DatasetNames.BdeactivitiesBq}.createdAt`,
        subject: `${DatasetNames.BdeactivitiesBq}.subject`,
        category: `${DatasetNames.BdeactivitiesBq}.category`,
        leadId: `${DatasetNames.BdeactivitiesBq}.leadId`,
        Id: `${DatasetNames.BdeactivitiesBq}.Id`,
        createdBy: `${DatasetNames.BdeactivitiesBq}.createdBy`,
        activityId: `${DatasetNames.BdeactivitiesBq}.activityId`,
        activityScore: `${DatasetNames.BdeactivitiesBq}.activityScore`,
        status: `${DatasetNames.BdeactivitiesBq}.status`,
        totalActivityScore: `${DatasetNames.BdeactivitiesBq}.TotalActivityScore`,
        buAverage: `${DatasetNames.BdeactivitiesBq}.BUAverage`,
        count: `${DatasetNames.BdeactivitiesBq}.count`,
        nationalAverage: `${DatasetNames.BdeactivitiesBq}.NationalAverage`,
        taskActivity: `${DatasetNames.BdeactivitiesBq}.taskActivity`,
        createdByRoleName: `${DatasetNames.BdeactivitiesBq}.createdByRoleName`,
        knownLanguages: `${DatasetNames.BdeactivitiesBq}.knownLanguages`,
        leadStage: `${DatasetNames.BdeactivitiesBq}.leadStage`,
        leadStatus: `${DatasetNames.BdeactivitiesBq}.leadStatus`,
        followUpDateTime: `${DatasetNames.BdeactivitiesBq}.followUpDateTime`,
        buh: `${DatasetNames.BdeactivitiesBq}.buh`,
        inHead: `${DatasetNames.BdeactivitiesBq}.inHead`,
    },
    Targets: {
        targetAmount: `${DatasetNames.Targets}.targetAmount`,
        targetMonth: `${DatasetNames.Targets}.targetMonth`,
        displayName: `${DatasetNames.Targets}.displayName`,
        roleName: `${DatasetNames.Targets}.roleName`,
        targetMonth: `${DatasetNames.Targets}.targetMonth`,
        TotalTargetAmount: `${DatasetNames.Targets}.TotalTargetAmount`,
    },
    Territorymappings: {
        territoryName: `${DatasetNames.Territorymappings}.territoryName`,
        territoryCode: `${DatasetNames.Territorymappings}.territoryCode`,
        countryName: `${DatasetNames.Territorymappings}.countryName`,
        stateName: `${DatasetNames.Territorymappings}.stateName`,
        stateCode: `${DatasetNames.Territorymappings}.stateCode`,
        countryCode: `${DatasetNames.Territorymappings}.countryCode`,
        cityName: `${DatasetNames.Territorymappings}.cityName`,
        cityCode:`${DatasetNames.Territorymappings}.cityCode`,

    },
    Purchaseorders: {
        quotationCode: `${DatasetNames.Purchaseorders}.quotationCode`,
        purchaseOrderCode: `${DatasetNames.Purchaseorders}.purchaseOrderCode`,
        schoolCode: `${DatasetNames.Purchaseorders}.schoolCode`,
        schoolName: `${DatasetNames.Purchaseorders}.schoolName`,
        product: `${DatasetNames.Purchaseorders}.product`,
        status: `${DatasetNames.Purchaseorders}.status`,
        createdByName: `${DatasetNames.Purchaseorders}.createdByName`,
        createdByRoleName: `${DatasetNames.Purchaseorders}.createdByRoleName`,
        poAmount: `${DatasetNames.Purchaseorders}.poAmount`,
        createdAt: `${DatasetNames.Purchaseorders}.createdAt`,
        totalRecords: `${DatasetNames.Purchaseorders}.totalRecords`,
        approvalStatus: `${DatasetNames.Purchaseorders}.approvalStatus`,
    },
    Quotations: {
        quotationCode: `${DatasetNames.Quotations}.quotationCode`,
        schoolCode: `${DatasetNames.Quotations}.schoolCode`,
        schoolName: `${DatasetNames.Quotations}.schoolName`,
        createdAt: `${DatasetNames.Quotations}.FormatedCreatedDate`,
        approvalStatus: `${DatasetNames.Quotations}.approvalStatus`,
        createdByName: `${DatasetNames.Quotations}.createdByName`,
        createdByRoleName: `${DatasetNames.Quotations}.createdByRoleName`,
        MergedProductName: `${DatasetNames.Quotations}.MergedProductName`,
        productItemSalePriceSum: `${DatasetNames.Quotations}.TotalSalePrice`,
        updatedAt: `${DatasetNames.Quotations}.updatedAt`,
        totalRecords: `${DatasetNames.Quotations}.totalRecords`,
        TotalSalePrice: `${DatasetNames.Quotations}.TotalSalePrice`,
        groupCode: `${DatasetNames.Quotations}.groupCode`,
        createdat: `${DatasetNames.Quotations}.createdAt`,
        productName: `${DatasetNames.Quotations}.productName`,
        


    },
    Implementationforms: {
        impFormNumber: `${DatasetNames.Implementationforms}.impFormNumber`,
        schoolCode: `${DatasetNames.Implementationforms}.schoolCode`,
        schoolName: `${DatasetNames.Implementationforms}.schoolName`,
        productName: `${DatasetNames.Implementationforms}.productName`,
        approvalStatus: `${DatasetNames.Implementationforms}.approvalStatus`,
        createdByName: `${DatasetNames.Implementationforms}.createdByName`,
        createdByRoleName: `${DatasetNames.Implementationforms}.createdByRoleName`,
        assignedEngineerName: `${DatasetNames.Implementationforms}.assignedEngineerName`,
        createdAt: `${DatasetNames.Implementationforms}.createdAt`,
        purchaseOrderCode: `${DatasetNames.Implementationforms}.purchaseOrderCode`,
        quotationCode: `${DatasetNames.Implementationforms}.quotationCode`,
        schoolCityName: `${DatasetNames.Implementationforms}.schoolCityName`,
        schoolStateName: `${DatasetNames.Implementationforms}.schoolStateName`,
        productDetails: `${DatasetNames.Implementationforms}.productDetails`,
    },
    SyllabusMappingMaster: {
        boardId: `${DatasetNames.SyllabusMappingMaster}.boardId`,
        boardName: `${DatasetNames.SyllabusMappingMaster}.boardName`,
        classId: `${DatasetNames.SyllabusMappingMaster}.classId`,
        className: `${DatasetNames.SyllabusMappingMaster}.className`
    },
    SyllabusBoardClassMaster: {
        boardId: `${DatasetNames.SyllabusBoardClassMaster}.boardId`,
        boardName: `${DatasetNames.SyllabusBoardClassMaster}.boardName`,
        classId: `${DatasetNames.SyllabusBoardClassMaster}.classId`,
        className: `${DatasetNames.SyllabusBoardClassMaster}.className`,
        syllabusOrder: `${DatasetNames.SyllabusBoardClassMaster}.syllabusOrder`
    },
    Leadowners: {
        assignedToRoleName: `${DatasetNames.Leadowners}.assignedToRoleName`,
        assignedToProfileName: `${DatasetNames.Leadowners}.assignedToProfileName`,
        assignedToRoleName: `${DatasetNames.Leadowners}.assignedToRoleName`,
    },
    Ledger: {
        totalRecords:`${DatasetNames.Ledger}.totalRecords`,
        product:`${DatasetNames.Ledger}.product`,
        businessUnit:`${DatasetNames.Ledger}.businessUnit`,
        osAmount:`${DatasetNames.Ledger}.osAmount`,
        osMonths:`${DatasetNames.Ledger}.osMonths`,
        totalContractValue:`${DatasetNames.Ledger}.totalContractValue`,
        schoolCode:`${DatasetNames.Ledger}.schoolCode`,
        schoolName:`${DatasetNames.Ledger}.schoolName`,
        city:`${DatasetNames.Ledger}.city`,
        cityCode:`${DatasetNames.Ledger}.cityCode`,
        productName:`${DatasetNames.Ledger}.productName`,
        pinCode:`${DatasetNames.Ledger}.pinCode`,
        address:`${DatasetNames.Ledger}.address`,
    }

}

export const stateCodeMapping = {
    AP: "37",
    AS: "18",
    BH: "10",
    CG: "22",
    DL: "07",
    GA: "30",
    GJ: "24",
    HR: "06",
    HP: "02",
    JK: "01",
    JH: "20",
    KA: "29",
    KL: "32",
    MP: "23",
    MH: "27",
    OR: "21",
    OD: "21",
    PB: "03",
    RJ: "08",
    TN: "33",
    TS: "36",
    TR: "16",
    UP: "09",
    UT: "05",
    WB: "19",
    CH: "04",
    DN: "26",
    ME: "17",
    MI: "15",
    NL: "13",
    PY: "34",
    SK: "11",
    AN: "35",
    AR: "12",
    DD: "25",
    LD: "31",
    MN: "14",
    OT: "97",
    OC: "99",
    LA: "38"
}
export default CubeDataset
